WORKDIR:
  "path/to/snakemake_folder/minimal_example"
RUN_FILES:
  "path/to/snakemake_folder/MultiSample.MultiGroupComp.AdjVars.Scripts"
RUN_FILESIR:
  "path/to/snakemake_folder/MultiSample.MultiGroupComp.AdjVars.Scripts.IR"
INTRONBED_FILE:
  "path/to/snakemake_folder/JunctionCalling.Pipeline.Scripts/annotation_reference/leafviz_all_introns_cleaned.bed"
SAMPLES:
  - "SAMPLEID"
NPERM:
  100000
JOB_NAME:
  "snakemake_part3"
COMP_GROUPS_COLUMN:
  "GENOTYPECOLUMN" # Replace with the column name where the comparison groups are defined
COMP1:
  "WT"
COMP2:
  "MUT"
CELL_GROUPS_COLUMN:
  "CELLTYPE" # Replace with the column name that allows to filter the cells that will be used for the analysis
GROUPLIST:
  "ALL"
OUTPUTDIR:
  "output_dir"
JUNC_COV_THRESH:
  5
N_CHUNK:
  5
