executor: cluster-generic

default-resources:
  - mem_mb=200000
  - runtime=7200

cluster-generic-submit-cmd:
  sbatch
    --cpus-per-task=10
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --partition=cpu
    --job-name={rule}
    --output=logs/{rule}/{rule}.out
    --error=logs/{rule}/{rule}.err

max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50 # Check what the max is
keep-going: True
rerun-incomplete: True
printshellcmds: True
  
set-resources:
  rename_final_folder:
    mem_mb: 1000
  copy_combined_files:
    mem_mb: 1000
  split_clusters:
    mem_mb: 500000
  