WORKDIR:
  "/path/to/your/workdir"
RUN_FILES:
  "path/to/snakemake/pipeline/JunctionCalling.Pipeline.Scripts"
SICERLORE_VERSION:
  "2.1"
SAMPLES:
  - "SAMPLENAME"
JOB_NAME:
  "snakemake_part2"
OUTPUTDIR:
  "splicing_runs_folder"
METADATADIR:
  "/sample_metadata_ont/"
LIBRARY_TYPE:
  "ONT"